use super::menu::MenuItem;

pub fn get_default_editor_menus() -> Vec<MenuItem> {
    vec![
        MenuItem {
            id: "file".to_string(),
            label: "File".to_string(),
            action: false,
            shortcut: None,
            enabled: true,
            checked: None,
            submenu: Some(vec![
                MenuItem {
                    id: "file.new".to_string(),
                    label: "New".to_string(),
                    action: true,
                    shortcut: Some("Ctrl+N".to_string()),
                    enabled: true,
                    checked: None,
                    submenu: None,
                },
                MenuItem {
                    id: "file.open".to_string(),
                    label: "Open...".to_string(),
                    action: true,
                    shortcut: Some("Ctrl+O".to_string()),
                    enabled: true,
                    checked: None,
                    submenu: None,
                },
                MenuItem {
                    id: "file.save_as".to_string(),
                    label: "Save As...".to_string(),
                    action: true,
                    shortcut: Some("Ctrl+Shift+S".to_string()),
                    enabled: true,
                    checked: None,
                    submenu: None,
                },
                MenuItem {
                    id: "file.exit".to_string(),
                    label: "Exit".to_string(),
                    action: true,
                    shortcut: Some("Alt+F4".to_string()),
                    enabled: true,
                    checked: None,
                    submenu: None,
                },
            ]),
        },
        MenuItem {
            id: "edit".to_string(),
            label: "Edit".to_string(),
            action: false,
            shortcut: None,
            enabled: true,
            checked: None,
            submenu: Some(vec![
                MenuItem {
                    id: "edit.undo".to_string(),
                    label: "Undo".to_string(),
                    action: true,
                    shortcut: Some("Ctrl+Z".to_string()),
                    enabled: true,
                    checked: None,
                    submenu: None,
                },
                MenuItem {
                    id: "edit.redo".to_string(),
                    label: "Redo".to_string(),
                    action: true,
                    shortcut: Some("Ctrl+Y".to_string()),
                    enabled: true,
                    checked: None,
                    submenu: None,
                },
                MenuItem {
                    id: "edit.separator1".to_string(),
                    label: "-".to_string(),
                    action: false,
                    shortcut: None,
                    enabled: false,
                    checked: None,
                    submenu: None,
                },
                MenuItem {
                    id: "edit.cut".to_string(),
                    label: "Cut".to_string(),
                    action: true,
                    shortcut: Some("Ctrl+X".to_string()),
                    enabled: true,
                    checked: None,
                    submenu: None,
                },
                MenuItem {
                    id: "edit.copy".to_string(),
                    label: "Copy".to_string(),
                    action: true,
                    shortcut: Some("Ctrl+C".to_string()),
                    enabled: true,
                    checked: None,
                    submenu: None,
                },
                MenuItem {
                    id: "edit.paste".to_string(),
                    label: "Paste".to_string(),
                    action: true,
                    shortcut: Some("Ctrl+V".to_string()),
                    enabled: true,
                    checked: None,
                    submenu: None,
                },
            ]),
        },
        MenuItem {
            id: "view".to_string(),
            label: "View".to_string(),
            action: false,
            shortcut: None,
            enabled: true,
            checked: None,
            submenu: Some(vec![
                MenuItem {
                    id: "view.theme".to_string(),
                    label: "Theme".to_string(),
                    action: false,
                    shortcut: None,
                    enabled: true,
                    checked: None,
                    submenu: Some(vec![
                        MenuItem {
                            id: "view.theme.light".to_string(),
                            label: "Light".to_string(),
                            action: true,
                            shortcut: None,
                            enabled: true,
                            checked: Some(false),
                            submenu: None,
                        },
                        MenuItem {
                            id: "view.theme.dark".to_string(),
                            label: "Dark".to_string(),
                            action: true,
                            shortcut: None,
                            enabled: true,
                            checked: Some(true),
                            submenu: None,
                        },
                    ]),
                },
            ]),
        },
        MenuItem {
            id: "help".to_string(),
            label: "Help".to_string(),
            action: false,
            shortcut: None,
            enabled: true,
            checked: None,
            submenu: Some(vec![
                MenuItem {
                    id: "help.about".to_string(),
                    label: "About".to_string(),
                    action: true,
                    shortcut: None,
                    enabled: true,
                    checked: None,
                    submenu: None,
                },
            ]),
        },
    ]
}